version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      
      - docker build -f PromotionsSG.API.Login.Dockerfile -t loginapi .
      - docker build -f PromotionsSG.API.CustomerProfile.Dockerfile -t customerprofileapi .
      - docker build -f PromotionsSG.API.ShopProfile.Dockerfile -t shopprofileapi .
      - docker build -f PromotionsSG.API.Promotion.Dockerfile -t promotionapi .
      - docker build -f PromotionsSG.API.Claim.Dockerfile -t claimapi .
      - docker build -f PromotionsSG.API.Feedback.Dockerfile -t feedbackapi .
      - docker build -f PromotionsSG.API.Recommendation/Dockerfile -t recommendationapi .
      - docker build -f PromotionsSG.API.Notification/Dockerfile -t notificationapi .
      - docker build -f PromotionsSG.Presentation.WebPortal.Dockerfile -t webportalapi .
      
      - docker tag loginapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/loginapi:latest
      - docker tag customerprofileapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/customerprofileapi:latest
      - docker tag shopprofileapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/shopprofileapi:latest
      - docker tag promotionapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/promotionapi:latest
      - docker tag claimapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/claimapi:latest
      - docker tag feedbackapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/feedbackapi:latest
      - docker tag recommendationapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/recommendationapi:latest
      - docker tag notificationapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/notificationapi:latest
      - docker tag webportalapi:latest 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/webportalapi:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/loginapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/customerprofileapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/shopprofileapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/promotionapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/claimapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/feedbackapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/recommendationapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/notificationapi:latest
      - docker push 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/webportalapi:latest
      
      - printf '[{"name":"promotionsg-container--webportal-2","imageUri":"%s"}]' 702668669288.dkr.ecr.ap-southeast-1.amazonaws.com/webportalapi:latest > imagedefinitions.json
      - aws ecs list-tasks --cluster "promotionsg-cluster-2" --output text | awk '{print $2}' | while read line ; do aws ecs stop-task --task "$line" --cluster "promotionsg-cluster-2" ; done
      
artifacts:
  files:
    - imagedefinitions.json
  name: BuildArtifact