CREATE TABLE [dbo].[CodeTable](
	[CodeTableId] int IDENTITY(1,1),
	[Code] [varchar](250) NULL,
	[CodeDesc] [varchar](500) NULL,
 CONSTRAINT [PK_CodeTable] PRIMARY KEY CLUSTERED 
(
	[CodeTableId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


